name: Incoming Checks
on: [pull_request, push]

env:
  GO_VERSION: "1.16"

jobs:
  go_mod:
    # Ignore duplicate events for local repository pull requests
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    name: go mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: go mod
        run: |
          echo "==> Checking source code with go mod vendor..."
          go mod tidy
          git diff --exit-code -- go.mod go.sum || \
            (echo; echo "Unexpected difference in go.mod/go.sum files. Run 'go mod tidy' command or revert any go.mod/go.sum changes and commit."; exit 1)
          echo "==> Checking source code with go mod vendor..."
          go mod vendor
          git diff --compact-summary --exit-code -- vendor || \
            (echo; echo "Unexpected difference in vendor/ directory. Run 'go mod vendor' command or revert any go.mod/go.sum/vendor changes and commit."; exit 1)
  go_test:
    # Ignore duplicate events for local repository pull requests
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go test ./...
  goreleaser:
    # Ignore duplicate events for local repository pull requests
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)
    name: goreleaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: goreleaser check
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check
      - name: goreleaser build
        uses: goreleaser/goreleaser-action@v2
        with:
          args: build --snapshot
